class DocumentKeysDetectionPatterns:

    def __init__(self):
        self.patterns = []
        phantom = (1.4, ["origin",
                         "xmlEncoding",
                         "xmlVersion",
                         "xmlStandalone",
                         "selectedStylesheetSet",
                         "preferredStylesheetSet",
                         "webkitVisibilityState",
                         "webkitHidden",
                         "onbeforecopy",
                         "onbeforecut",
                         "onbeforepaste",
                         "onsearch",
                         "oncancel",
                         "oncuechange",
                         "onmousewheel",
                         "webkitIsFullScreen",
                         "webkitCurrentFullScreenElement",
                         "webkitFullscreenEnabled",
                         "webkitFullscreenElement",
                         "onwebkitfullscreenchange",
                         "onwebkitfullscreenerror",
                         "registerElement",
                         "caretRangeFromPoint",
                         "webkitCancelFullScreen",
                         "webkitExitFullscreen",
                         "releaseCapture", #added
                         "mozSetImageElement",
                         "mozCancelFullScreen",
                         "enableStyleSheetsForSet",
                         "caretPositionFromPoint",
                         "onbeforescriptexecute",
                         "onafterscriptexecute",
                         "mozFullScreen",
                         "mozFullScreenEnabled",
                         "mozFullScreenElement",
                         "selectedStyleSheetSet",
                         "lastStyleSheetSet",
                         "preferredStyleSheetSet",
                         "styleSheetSets",
                         "ondragexit",
                         "onloadend",
                         "onshow",
                         "onmozfullscreenchange",
                         "onmozfullscreenerror",
                         "onanimationcancel",
                         "onanimationend",
                         "onanimationiteration",
                         "onanimationstart",
                         "ontransitioncancel",
                         "ontransitionend",
                         "ontransitionrun",
                         "ontransitionstart",
                         "onwebkitanimationend",
                         "onwebkitanimationiteration",
                         "onwebkitanimationstart",
                         "onwebkittransitionend"])
        seleniumChrome  = (1.4, ["\$cdc","\$wdc","\$[a-z]dc"])
        nightmare = (1.4, ["onvisibilitychange", "onshow"])
        seleniumIE = (1.4, ["__IE_DEVTOOLBAR_CONSOLE_EVAL_ERROR", "__IE_DEVTOOLBAR_CONSOLE_EVAL_ERRORCODE",
        "__webdriver_script_fn"])
        general = (1.4, ["_IDE([^a-zA-z]|_)", "callSelenium", "_Selenium_IDE_Recorder","selenium",
        "nightmare","_selenium", "fxdriver_evaluate","driver_unwrapped", "webdriver_unwrapped",
        "driver_evaluate", "selenium_unwrapped","fxdriver_unwrapped", "webdriver_evaluate", "webdriver-evaluate",
        "selenium_evaluate", "webdriver_script_function", "webdriver_script_func"])
        self.patterns.extend((phantom, seleniumChrome, nightmare, seleniumIE, general))