class WindowKeysDetectionPatterns:

    def __init__(self):
        self.patterns = []
        self.name = "WindowKeys"
        phantom = (1.4, "PhantomJS", [
            "origin",
            "customElements",
            "external",
            "onanimationend",
            "onanimationiteration",
            "onanimationstart",
            "isSecureContext",
            "oncancel",
            "onclose",
            "oncuechange",
            "ontoggle",
            "onwheel",
            "onauxclick",
            "ongotpointercapture",
            "onlostpointercapture",
            "onpointerdown",
            "onpointermove",
            "onpointerup",
            "onpointercancel",
            "onpointerover",
            "onpointerout",
            "onpointerenter",
            "onpointerleave",
            "onlanguagechange",
            "onrejectionhandled",
            "onunhandledrejection",
            "requestIdleCallback",
            "cancelIdleCallback",
            "createImageBitmap",
            "caches",
            "ondevicemotion",
            "ondeviceorientation",
            "ondeviceorientationabsolute",
            "webkitStorageInfo",
            "fetch",
            "speechSynthesis",
            "webkitRequestFileSystem",
            "webkitResolveLocalFileSystemURL",        
            "TEMPORARY",
            "PERSISTENT",
            "offscreenBuffering", #added
            "event",
            "webkitIndexedDB",
            "ontouchmove",
            "ontouchstart",
            "webkitNotifications",
            "ontouchend",
            "ontouchcancel",
            "_phantom",
            "callPhantom",
            "showModalDialog",
            "webkitConvertPointFromNodeToPage",
            "webkitConvertPointFromPageToNode",
            "webkitCancelRequestAnimationFrame",
        ])
        nightmare = (1.4, "Nightmare", ["__nightmare", "onshow"])
        misc = (1.4, "Misc", ["window.chrome", "window.attr", "onbeforeprint", "onafterprint", "onmessageerror",
        "onappinstalled", "onbeforeinstallprompt",
        "getMatchedCSSRules", #missing
        "console",
        ])
        seleniumIE = (1.4, "SelIE", ["__BROWSERTOOLS_CONSOLE_SAFEFUNC", "__BROWSERTOOLS_CONSOLE_BREAKMODE_FUNC",
        "__BROWSERTOOLS_CONSOLE","__BROWSERTOOLS_EMULATIONTOOLS_ADDED","__BROWSERTOOLS_DOMEXPLORER_ADDED",
        "__BROWSERTOOLS_MEMORYANALYZER_ADDED","$0","$1","$2","$3","$4","__BROWSERTOOLS_NETWORK_TOOL_ADDED","__BROWSERTOOLS_DEBUGGER"])
        self.patterns.extend((phantom, nightmare, misc, seleniumIE))
